#!/usr/bin/env python

# Copyright (c) 2017 Computer Vision Center (CVC) at the Universitat Autonoma de
# Barcelona (UAB).
#
# This work is licensed under the terms of the MIT license.
# For a copy, see <https://opensource.org/licenses/MIT>.

# Allows visualising a 2D map generated by vehicles.

"""
  Welcome to CARLA map visualizer
"""
import sys

try:
    import pygame
    from pygame.locals import K_DOWN
    from pygame.locals import K_LEFT
    from pygame.locals import K_RIGHT
    from pygame.locals import K_UP
    from pygame.locals import K_ESCAPE
except ImportError:
    raise RuntimeError('cannot import pygame, make sure pygame package is installed')


SCREEN_WIDTH  = 500
SCREEN_HEIGHT = 500


class Location(object):
    def __init__(self, x, y):
        self.x = x
        self.y = y
    def __add__(self, other):
        self.x += other.x
        self.y += other.y
        return Location(self.x + other.x, self.y + other.y)

class Vehicle(object):
    def __init__(self, location, size, color):
        self.location = location
        self.size = size
        self.color = color

    def draw(self, display):
        pygame.draw.rect(display, self.color, (self.location.x, self.location.y, self.size[0], self.size[1]) )


#Handles keyboard and mouse input
class KeyboardInput(object):
    def parse_events(self, vehicle):
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                pygame.quit()
                sys.exit()
            elif event.type == pygame.KEYUP:
                # Quick actions
                if event.key == K_ESCAPE:
                    pygame.quit()
                    sys.exit()

        keys = pygame.key.get_pressed()
        if keys[pygame.K_LEFT]:
            vehicle.location += Location(x=-0.1,y=0)
        if keys[pygame.K_RIGHT]:
            vehicle.location += Location(x=0.1,y=0)
        if keys[pygame.K_UP]:
            vehicle.location += Location(x=0,y=-0.1)
        if keys[pygame.K_DOWN]:
            vehicle.location += Location(x=0,y=0.1)


def game_loop():
    print("Game Loop called")

    pygame.init()
    display = pygame.display.set_mode((SCREEN_WIDTH, SCREEN_HEIGHT))
    pygame.display.set_caption('Map Visualizer')

    # Initialize Input
    keyboard_input = KeyboardInput()

    # Create vehicle
    vehicle = Vehicle(location=Location(0,0), size=(100, 100), color=(250,0,0))

    while True:

        # Handle events
        keyboard_input.parse_events(vehicle)

        display.fill((0, 0, 0))

        vehicle.draw(display)

        pygame.display.update()

def main():
    game_loop()


if __name__ == '__main__':
    main()